### PR TITLE
Add HTML highlighting inside strings

### PR DESCRIPTION
**Pull request by natebosch**

### CODE REVIEW

**Comment by natebosch** [comment]
I think this could be useful for things like `template` inlined in an angular component annotation.

I'm pretty confident this should work with anyone's vim setup since `html` is a syntax that ships with vim. I'm open to gating this behind an option if anyone is worried about it. PHP syntax has this off by default but you can turn it on with `let php_htmlInStrings = 1`.

**Comment by natebosch** [comment]
I think it should be minimal, but I'm generally on a fast enough machine that I don't notice 'heavy' plugins slowing things down.

I'll take a stab at gating it behind a flag - what do you think the default should be? The conservative thing would be to default to off, but this is also something with low discover-ability so having it on might mean that more people who might want it would get it.

**Comment by natebosch** [comment]
I went ahead and set it off by default.

**Comment by cbracken** [comment]
Thanks; yeah I would do off by default. But then again I'm not much of a web guy. The note in the readme looks good to me!

**Pull request merged**
