### PR TITLE
Replace GIF demos of the provided vim commands

### PR DESCRIPTION
**Pull request by smanilov**
The changes cannot be seen on my fork of the repo, as the links to the GIFs are kept absolute (pointing to dart-lang/dart-vim-plugin) as in the original repo.

### CODE REVIEW

**Comment by cbracken** [comment]
Thanks!
1. Please sign the CLA
2. The new images are much smaller -- enough that I can barely read the characters on a MacBook Pro. Not sure if the issue if GitHub's presentation of them or an actual issue. I'll take a look in the AM.

**Comment by smanilov** [comment]
Hey,
Sorry for the opinionated commit message. I was referring to the font and the size of the original GIFs. I will close this PR and submit the proposed change via depot_tools.

**Comment by cbracken** [comment]
SGTM. Whether you submit via depot_tools or not, we can't take the PR until you sign the CLA. Please do that before submitting.

Haven't had a look at the gifs locally; been swamped with other reviews this morning. I'll do that in a moment.

**Comment by cbracken** [comment]
Alright yanked everything down. Agreed the new GIFs look better to me including the dimensions.

One issue I see is that the old gifs are `418k + 687k + 571k = 1.7M` in size, but the new ones are `3.5M + 3.0M + 4.3M = 10.8M`. Any way to get the size down?

**Comment by cbracken** [comment]
Merged as 18ca401. Thanks!

**Pull request closed without merging**
