### PR TITLE
Specify pathogen.

### PR DESCRIPTION
**Pull request by colintsteele**
As someone who has never used Pathogen, although it was clear to see I needed Pathogen, I was not sure how to tie them together.  I think this change makes it more clear and should get users up and running with less confusion.

### CODE REVIEW

**Comment by colintsteele** [comment]
I signed it!

**Comment by cbracken** [comment]
Thanks for the PR. FYI - Pathogen is not required for this vim plugin. In `README.md` we recommend Vundle (another package manager for vim), though it's not technically required either.

If we do mention Pathogen, perhaps the answer is to break out two sections: one with the existing instructions for Vundle and a separate one for Pathogen. I haven't used Pathogen, so I'm not aware of what's required, but if you are then a patch that adds a section with full instructions for getting it running under Pathogen is definitely welcome!

**Comment by cbracken** [comment]
Actually looking at README.md, it seems someone has changed it to mention Pathogen, but the instructions are still Vundle-specific. I'll dig through the history to figure out what went on.

**Comment by colintsteele** [comment]
No sweat, I hadn't seen mention of Vundle and it refers to Pathogen as required, so I thought this would help.  I definitely think a "for pathogen do this: \n or if you're using vundle do this:" would be a good change.

**Comment by cbracken** [comment]
Yeah a bit of digging and it looks like I'm definitely mis-remembering, it's mentioned Pathogen since 2014. That being the case, the patch looks great as is!

The confusion comes from the fact that we recommend installation via Vundle in the internal instructions for use at Google and I've clearly mixed the two up :)

**Comment by cbracken** [comment]
lgtm - nicely done

**Comment by cbracken** [comment]
@natebosch any preference for Pathogen vs Vundle vs something else? I remember at the time I started using a package manager in Vim, Vundle was the new hotness, and I found a lot more shiny new docs on it than Pathogen, but IIRC as of vim 8, there's some form of built-in packaging support. Perhaps we should investigate that?

**Comment by natebosch** [comment]
I think we should have examples for a couple options but avoid going into too much detail and instead have links to docs for each one. [vim-plug](https://github.com/junegunn/vim-plug) is the nicest one, but vundle is still really popular.

I haven't personally tried the vim8 package managements and don't know that I could provide accurate instructions.

**Comment by cbracken** [comment]
Filed #41

**Comment by colintsteele** [comment]
No problem, guys!  I personally have used vim-plug the most, so mentioning that would be a plus for people like me.

**Pull request merged**
