### PR TITLE
Add highlighting for user defined types (#74)

### PR DESCRIPTION
**Pull request by yasukotelin**
Hello!

I start to write Flutter with Vim recently. 
I just found out this [issue ](https://github.com/dart-lang/dart-vim-plugin/issues/74)when I want my defined types to be highlighted .

I added highlight options `dart_highlight_types`. default is false.

image

Thank you!

### CODE REVIEW

**Comment by natebosch** [comment]
> Given that we default `dartType` highlighting to on, I wonder if we should just default this to on and not have a flag, or have a single flag that covers both the builtins and the user-defined types?

The last time I looked at this I felt that the result of highlighting everything that started with a capital letter was a bit much:

https://github.com/dart-lang/dart-vim-plugin/issues/74#issuecomment-457417554

We could consider choosing something other than `TypeDef` for highlighting keywords like `class` and `extends` perhaps.

@cbracken - have you tried this enabled locally for a while to see how it feels? If I'm the only one who finds it off-putting we can certainly move forward and I can change my config locally.

**Comment by cbracken** [comment]
I patched it in locally and it felt like an improvement to me. Caveat is that I don't use a custom colour scheme, just the built-in one.

**Comment by natebosch** [comment]
I'm curious how many common colorschemes differentiate between `Type`, `Typedef`, and `StorageClass`, mine doesn't currently and I checked a bunch of the default ones that ship with vim and didn't notice any that did. With this change I'm worried about lines like:

```
class MockFoo extends Mock implements Foo {}
```

This becomes very monotone, whereas before the keywords `class`, `extends`, and `implements` all stood out.

I think, though, that I can work around this by setting some new highlighting for `Type` and `Typedef` in my config.

I think there are separate things we might consider changing, like making `dartClassDecl` map to `dartTypeDef` instead of `dartStorageClass`, but that's not something that needs to have an impact here.

I do agree that we can default this to on.

**Comment by natebosch** [comment]
Merged to master. Thanks!

**Pull request merged**
